# Generated by Django 2.2.26 on 2022-03-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WOF', '0002_auto_20220308_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=60, null=True)),
                ('degree', models.CharField(default='', max_length=80, null=True)),
                ('level', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Student Users',
            },
        ),
        migrations.RenameField(
            model_name='university',
            old_name='Location',
            new_name='location',
        ),
        migrations.DeleteModel(
            name='StudentUserProfile',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WOF.University'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
